name: medgemma
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.15.3
  - aom=3.9.1
  - attr=2.5.2
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cairo=1.18.4
  - cpython=3.10.19
  - cuda-cudart=12.1.105
  - cuda-cudart_linux-64=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.1.105
  - cuda-runtime=12.1.0
  - cuda-version=12.1
  - dav1d=1.2.1
  - dbus=1.16.2
  - ffmpeg=8.0.1
  - filelock=3.20.3
  - fmt=12.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - fsspec=2026.1.0
  - gdk-pixbuf=2.44.5
  - giflib=5.2.2
  - glslang=16.2.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=12.3.2
  - icu=78.2
  - intel-gmmlib=22.9.0
  - intel-media-driver=25.3.4
  - jinja2=3.1.6
  - kaldi=5.5.1172
  - lame=3.100
  - lcms2=2.18
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - level-zero=1.28.0
  - libabseil=20250512.1
  - libass=0.17.4
  - libavif16=1.3.0
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcap=2.77
  - libcblas=3.11.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libde265=1.0.15
  - libdeflate=1.25
  - libdrm=2.4.125
  - libegl=1.7.0
  - libexpat=2.7.3
  - libffi=3.5.2
  - libflac=1.5.0
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgl=1.7.0
  - libglib=2.86.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.2.0
  - libheif=1.19.7
  - libhwloc=2.12.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.1
  - liblapack=3.11.0
  - liblapacke=3.11.0
  - liblzma=5.8.2
  - libnpp=12.0.2.50
  - libnsl=2.0.1
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libogg=1.3.5
  - libopenvino=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-intel-cpu-plugin=2025.4.1
  - libopenvino-intel-gpu-plugin=2025.4.1
  - libopenvino-intel-npu-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6.1
  - libpciaccess=0.18
  - libpng=1.6.54
  - libprotobuf=6.31.1
  - librsvg=2.60.0
  - libsndfile=1.2.2
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libsystemd0=258.3
  - libtiff=4.7.1
  - libtorch=2.10.0
  - libudev1=258.3
  - libunwind=1.8.3
  - liburing=2.13
  - libusb=1.0.29
  - libuuid=2.41.3
  - libuv=1.51.0
  - libva=2.23.0
  - libvorbis=1.3.7
  - libvpl=2.15.0
  - libvpx=1.15.2
  - libvulkan-loader=1.4.341.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.13.1
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - markupsafe=3.0.3
  - mkl=2025.3.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.4.2
  - numpy=2.2.6
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openfst=1.8.4
  - openh264=2.6.0
  - openjpeg=2.5.4
  - openssl=3.6.1
  - optree=0.18.0
  - packaging=26.0
  - pango=1.56.4
  - pcre2=10.47
  - pillow=12.1.0
  - pip=26.0
  - pixman=0.46.4
  - pthread-stubs=0.4
  - pugixml=1.15
  - pulseaudio-client=17.0
  - pybind11=3.0.1
  - pybind11-abi=11
  - pybind11-global=3.0.1
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.10.0
  - pytorch-cuda=12.1
  - rav1e=0.7.1
  - readline=8.3
  - sdl2=2.32.56
  - sdl3=3.4.0
  - setuptools=80.10.2
  - shaderc=2025.5
  - sleef=3.9.0
  - snappy=1.2.2
  - spirv-tools=2026.1
  - svt-av1=4.0.0
  - sympy=1.14.0
  - tbb=2022.3.0
  - tk=8.6.13
  - torchaudio=2.10.0
  - torchcodec=0.9.1
  - torchvision=0.25.0
  - torchvision-extra-decoders=0.0.2
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wayland=1.24.0
  - wayland-protocols=1.47
  - wheel=0.46.3
  - x264=1!164.3095
  - x265=3.5
  - xkeyboard-config=2.46
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcursor=1.2.3
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.7
  - xorg-libxfixes=6.0.2
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.5
  - xorg-libxrender=0.9.12
  - xorg-libxscrnsaver=1.2.4
  - xorg-libxtst=1.2.5
  - zlib-ng=2.3.3
  - zstd=1.5.7
  - pip:
    - GitPython==3.1.46
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - PyYAML==6.0.3
    - accelerate==1.12.0
    - altair==6.0.0
    - anyio==4.12.1
    - attrs==25.4.0
    - bitsandbytes==0.49.1
    - blinker==1.9.0
    - cachetools==6.2.6
    - certifi==2026.1.4
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cuda-bindings==12.9.4
    - cuda-pathfinder==1.3.3
    - dnspython==2.8.0
    - dotenv==0.9.9
    - exceptiongroup==1.3.1
    - filelock==3.20.3
    - fsspec==2026.1.0
    - gitdb==4.0.12
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface_hub==1.3.7
    - idna==3.11
    - jsonschema==4.26.0
    - jsonschema-specifications==2025.9.1
    - mpmath==1.3.0
    - narwhals==2.16.0
    - networkx==3.4.2
    - numpy==2.2.6
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.5
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvshmem-cu12==3.4.5
    - nvidia-nvtx-cu12==12.8.90
    - packaging==26.0
    - pandas==2.3.3
    - protobuf==6.33.5
    - psutil==7.2.2
    - pyarrow==23.0.0
    - pydeck==0.9.1
    - pymongo==4.16.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytz==2025.2
    - referencing==0.37.0
    - regex==2026.1.15
    - requests==2.32.5
    - rpds-py==0.30.0
    - safetensors==0.7.0
    - shellingham==1.5.4
    - six==1.17.0
    - smmap==5.0.2
    - streamlit==1.54.0
    - sympy==1.14.0
    - tenacity==9.1.3
    - tokenizers==0.22.2
    - toml==0.10.2
    - torch==2.10.0
    - tornado==6.5.4
    - tqdm==4.67.2
    - transformers==5.0.0
    - triton==3.6.0
    - typer-slim==0.21.1
    - typing_extensions==4.15.0
    - tzdata==2025.3
    - urllib3==2.6.3
    - watchdog==6.0.0

prefix: "/home/medigrass/miniforge3/envs/medgemma"
